apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "training.fullname" . }}-shell
  labels:
    {{- include "training.labels" . | nindent 4 }}
    {{- include "training.shell.selectorLabels" . | nindent 4 }}
spec:
  serviceName: {{ include "training.fullname" . }}-shell
  replicas: 1
  podManagementPolicy: Parallel
  {{- if .Values.persistence.enabled }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
  {{- end }}
  selector:
    matchLabels:
      {{- include "training.shell.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "training.shell.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "training.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      enableServiceLinks: false
      automountServiceAccountToken: false
      hostname: {{ include "training.fullname" . }}-shell
      containers:
        - name: shell
          image: "{{ .Values.shell.image.repository }}:{{ .Values.shell.image.tag }}"
          imagePullPolicy: {{ .Values.shell.image.pullPolicy }}
          {{- with .Values.shell.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.shell.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: USERNAME
              value: {{ .Values.username | quote }}
            - name: UUID
              value: {{ .Values.uuid | quote }}
          workingDir: {{ .Values.persistence.mountPath }}
          {{- with .Values.shell.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.shell.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: workspace
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: workspace
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
  {{- end }}
