apiVersion: v1
kind: Service
metadata:
  name: {{ include "kasm-kali.fullname" . }}
  labels:
    {{- include "kasm-kali.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.authProxy.enabled }}
      targetPort: http
      {{- else }}
      targetPort: vnc
      {{- end }}
      protocol: TCP
  selector:
    {{- include "kasm-kali.selectorLabels" . | nindent 4 }}
