apiVersion: v1
kind: Service
metadata:
  name: {{ include "kind-vm.fullname" . }}
  labels:
    {{- include "kind-vm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    kubevirt.io/domain: {{ include "kind-vm.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
