apiVersion: v1
kind: Service
metadata:
  name: {{ include "compose.fullname" . }}
  labels:
    {{- include "compose.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: entry
      protocol: TCP
      name: entry
  selector:
    {{- include "compose.selectorLabels" . | nindent 4 }}
