apiVersion: v2
name: compose
description: Run an unmodified docker-compose.yml as a single sandboxed (DinD) pod

maintainers:
  - name: aydev
    email: aydev@barbhack.fr

type: application

version: 0.1.0
appVersion: "28-dind"

kubeVersion: ">=1.19.0-0"

keywords:
  - compose
  - docker-compose
  - dind
  - sandbox
  - kata
  - oci

home: https://github.com/aydev/dploy-charts
sources:
  - https://github.com/aydev/dploy-charts
