{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "webshell.networkpolicy.name" . }}
  labels:
    {{- include "webshell.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      network: deny-all
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress: []
{{- end }}
