{{- $fullName := include "webshell.fullname" . -}}
{{- include "webshell.validateValues" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "webshell.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: Parallel
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
  selector:
    matchLabels:
      {{- include "webshell.container.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        network: deny-all
        {{- include "webshell.labels" . | nindent 8 }}
        app.kubernetes.io/component: container
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      enableServiceLinks: false
      automountServiceAccountToken: false
      serviceAccountName: {{ include "webshell.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostname: {{ $fullName }}
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - {{ $fullName }}
      containers:
        - name: container
          securityContext:
            {{- toYaml .Values.container.securityContext | nindent 12 }}
          image: "{{ .Values.container.image.repository }}:{{ .Values.container.image.tag }}"
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          command:
            - sleep
          args:
            - infinity
          livenessProbe:
            {{- toYaml .Values.container.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.container.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.container.resources | nindent 12 }}
          {{- with .Values.container.volumeMounts }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: {{ .Values.persistence.storageClass }}
        accessModes:
          {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
